name: scan_barcode
description: A flutter plugin to scan barcode. base the Google mlkit.
version: 0.1.0
homepage: https://github.com/fluttercandies/scan_barcode

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.3+2
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.5.0
  google_mlkit_commons: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
